# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CFSGSCFT.ui'
#
# Created: Sat Jan 19 15:12:17 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(871, 522)
        self.lineEdit_11 = QtGui.QLineEdit(Dialog)
        self.lineEdit_11.setGeometry(QtCore.QRect(1660, 1110, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_14 = QtGui.QLineEdit(Dialog)
        self.lineEdit_14.setGeometry(QtCore.QRect(1660, 1290, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(990, 1290, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_3 = QtGui.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(1200, 1170, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_2 = QtGui.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(1200, 1230, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QtCore.QRect(1200, 1110, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(990, 1230, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit = QtGui.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(1200, 1290, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(990, 1170, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_15 = QtGui.QLineEdit(Dialog)
        self.lineEdit_15.setGeometry(QtCore.QRect(1660, 1350, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_13 = QtGui.QLineEdit(Dialog)
        self.lineEdit_13.setGeometry(QtCore.QRect(1660, 1230, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(990, 1110, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_23 = QtGui.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(1320, 1350, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_12 = QtGui.QLineEdit(Dialog)
        self.lineEdit_12.setGeometry(QtCore.QRect(1660, 1170, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 10, 581, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(20, 350, 101, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_22 = QtGui.QLineEdit(Dialog)
        self.lineEdit_22.setGeometry(QtCore.QRect(290, 150, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName(_fromUtf8("lineEdit_22"))
        self.lineEdit_23 = QtGui.QLineEdit(Dialog)
        self.lineEdit_23.setGeometry(QtCore.QRect(290, 100, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setText(_fromUtf8(""))
        self.lineEdit_23.setObjectName(_fromUtf8("lineEdit_23"))
        self.label_14 = QtGui.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(20, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(20, 100, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_27 = QtGui.QLineEdit(Dialog)
        self.lineEdit_27.setGeometry(QtCore.QRect(730, 400, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName(_fromUtf8("lineEdit_27"))
        self.label_24 = QtGui.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(350, 400, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 450, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(580, 450, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 410, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 450, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lineEdit_24 = QtGui.QLineEdit(Dialog)
        self.lineEdit_24.setGeometry(QtCore.QRect(290, 200, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName(_fromUtf8("lineEdit_24"))
        self.label_16 = QtGui.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(20, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_25 = QtGui.QLineEdit(Dialog)
        self.lineEdit_25.setGeometry(QtCore.QRect(290, 250, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName(_fromUtf8("lineEdit_25"))
        self.label_17 = QtGui.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(20, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_18 = QtGui.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(20, 300, 261, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_28 = QtGui.QLineEdit(Dialog)
        self.lineEdit_28.setGeometry(QtCore.QRect(290, 300, 431, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName(_fromUtf8("lineEdit_28"))
        self.lineEdit_19 = QtGui.QLineEdit(Dialog)
        self.lineEdit_19.setGeometry(QtCore.QRect(730, 300, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName(_fromUtf8("lineEdit_19"))
        self.comboBox = QtGui.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(290, 350, 561, 41))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, _fromUtf8(""))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_12.setText(_translate("Dialog", "Saturday :", None))
        self.label_11.setText(_translate("Dialog", "Friday :", None))
        self.label_10.setText(_translate("Dialog", "Thursday :", None))
        self.label_9.setText(_translate("Dialog", "Wednesday :", None))
        self.label_23.setText(_translate("Dialog", "Total carbon footprints :", None))
        self.label_5.setText(_translate("Dialog", "Carbon Footprint tracker", None))
        self.label_13.setText(_translate("Dialog", "Model : ", None))
        self.label_14.setText(_translate("Dialog", "Day :", None))
        self.label_15.setText(_translate("Dialog", "Employee ID : ", None))
        self.label_24.setText(_translate("Dialog", "Total carbon footprints :", None))
        self.pushButton.setText(_translate("Dialog", "Go back to menu", None))
        self.pushButton_2.setText(_translate("Dialog", "Save", None))
        self.pushButton_3.setText(_translate("Dialog", "...", None))
        self.pushButton_4.setText(_translate("Dialog", "Clear", None))
        self.label_16.setText(_translate("Dialog", "Month :", None))
        self.label_17.setText(_translate("Dialog", "Year :", None))
        self.label_18.setText(_translate("Dialog", "Mode of transport :", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

