# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CFSGSDM.ui'
#
# Created: Sat Jan 19 15:12:45 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1051, 544)
        self.btn_save = QtGui.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(210, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.lw_book = QtGui.QListWidget(Dialog)
        self.lw_book.setGeometry(QtCore.QRect(310, 90, 731, 371))
        self.lw_book.setObjectName(_fromUtf8("lw_book"))
        self.btn_select = QtGui.QPushButton(Dialog)
        self.btn_select.setGeometry(QtCore.QRect(400, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_select.setFont(font)
        self.btn_select.setObjectName(_fromUtf8("btn_select"))
        self.btn_close = QtGui.QPushButton(Dialog)
        self.btn_close.setGeometry(QtCore.QRect(780, 470, 261, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        self.btn_close.setFont(font)
        self.btn_close.setObjectName(_fromUtf8("btn_close"))
        self.btn_delete = QtGui.QPushButton(Dialog)
        self.btn_delete.setGeometry(QtCore.QRect(590, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName(_fromUtf8("btn_delete"))
        self.btn_add = QtGui.QPushButton(Dialog)
        self.btn_add.setGeometry(QtCore.QRect(10, 470, 191, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(310, 10, 441, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lbl_phone = QtGui.QLabel(Dialog)
        self.lbl_phone.setGeometry(QtCore.QRect(10, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_phone.setFont(font)
        self.lbl_phone.setObjectName(_fromUtf8("lbl_phone"))
        self.lne_bookingid = QtGui.QLineEdit(Dialog)
        self.lne_bookingid.setGeometry(QtCore.QRect(120, 100, 181, 31))
        self.lne_bookingid.setReadOnly(True)
        self.lne_bookingid.setObjectName(_fromUtf8("lne_bookingid"))
        self.lbl_date = QtGui.QLabel(Dialog)
        self.lbl_date.setGeometry(QtCore.QRect(10, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_date.setFont(font)
        self.lbl_date.setObjectName(_fromUtf8("lbl_date"))
        self.lne_phone = QtGui.QLineEdit(Dialog)
        self.lne_phone.setGeometry(QtCore.QRect(120, 180, 181, 31))
        self.lne_phone.setObjectName(_fromUtf8("lne_phone"))
        self.lbl_airline = QtGui.QLabel(Dialog)
        self.lbl_airline.setGeometry(QtCore.QRect(10, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_airline.setFont(font)
        self.lbl_airline.setObjectName(_fromUtf8("lbl_airline"))
        self.lbl_name = QtGui.QLabel(Dialog)
        self.lbl_name.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.lne_name = QtGui.QLineEdit(Dialog)
        self.lne_name.setGeometry(QtCore.QRect(120, 140, 181, 31))
        self.lne_name.setObjectName(_fromUtf8("lne_name"))
        self.lbl_to = QtGui.QLabel(Dialog)
        self.lbl_to.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_to.setFont(font)
        self.lbl_to.setObjectName(_fromUtf8("lbl_to"))
        self.lbl_bookingid = QtGui.QLabel(Dialog)
        self.lbl_bookingid.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_bookingid.setFont(font)
        self.lbl_bookingid.setObjectName(_fromUtf8("lbl_bookingid"))
        self.lbl_from = QtGui.QLabel(Dialog)
        self.lbl_from.setGeometry(QtCore.QRect(10, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_from.setFont(font)
        self.lbl_from.setObjectName(_fromUtf8("lbl_from"))
        self.lne_date = QtGui.QLineEdit(Dialog)
        self.lne_date.setGeometry(QtCore.QRect(120, 340, 181, 31))
        self.lne_date.setObjectName(_fromUtf8("lne_date"))
        self.lne_phone_2 = QtGui.QLineEdit(Dialog)
        self.lne_phone_2.setGeometry(QtCore.QRect(120, 220, 181, 31))
        self.lne_phone_2.setObjectName(_fromUtf8("lne_phone_2"))
        self.lne_phone_3 = QtGui.QLineEdit(Dialog)
        self.lne_phone_3.setGeometry(QtCore.QRect(120, 260, 181, 31))
        self.lne_phone_3.setObjectName(_fromUtf8("lne_phone_3"))
        self.lne_phone_4 = QtGui.QLineEdit(Dialog)
        self.lne_phone_4.setGeometry(QtCore.QRect(120, 300, 181, 31))
        self.lne_phone_4.setObjectName(_fromUtf8("lne_phone_4"))
        self.lbl_date_2 = QtGui.QLabel(Dialog)
        self.lbl_date_2.setGeometry(QtCore.QRect(10, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_date_2.setFont(font)
        self.lbl_date_2.setObjectName(_fromUtf8("lbl_date_2"))
        self.lne_date_2 = QtGui.QLineEdit(Dialog)
        self.lne_date_2.setGeometry(QtCore.QRect(120, 380, 181, 31))
        self.lne_date_2.setObjectName(_fromUtf8("lne_date_2"))
        self.lbl_date_3 = QtGui.QLabel(Dialog)
        self.lbl_date_3.setGeometry(QtCore.QRect(10, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_date_3.setFont(font)
        self.lbl_date_3.setObjectName(_fromUtf8("lbl_date_3"))
        self.lne_date_3 = QtGui.QLineEdit(Dialog)
        self.lne_date_3.setGeometry(QtCore.QRect(120, 420, 181, 31))
        self.lne_date_3.setObjectName(_fromUtf8("lne_date_3"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.btn_save.setText(_translate("Dialog", "SAVE", None))
        self.btn_select.setText(_translate("Dialog", "SELECT", None))
        self.btn_close.setText(_translate("Dialog", "go back to menu", None))
        self.btn_delete.setText(_translate("Dialog", "DELETE", None))
        self.btn_add.setText(_translate("Dialog", "ADD", None))
        self.label_5.setText(_translate("Dialog", "Employee Database", None))
        self.lbl_phone.setText(_translate("Dialog", "Phone", None))
        self.lbl_date.setText(_translate("Dialog", "Zip", None))
        self.lbl_airline.setText(_translate("Dialog", "Adress", None))
        self.lbl_name.setText(_translate("Dialog", "Name", None))
        self.lbl_to.setText(_translate("Dialog", "Age", None))
        self.lbl_bookingid.setText(_translate("Dialog", "Employee ID", None))
        self.lbl_from.setText(_translate("Dialog", "Email", None))
        self.lbl_date_2.setText(_translate("Dialog", "Salary", None))
        self.lbl_date_3.setText(_translate("Dialog", "Bonus", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

