from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
class Ui_CFT(object):
    def setupUi(self, CFT):
        CFT.setObjectName(_fromUtf8("CFT"))
        CFT.resize(871, 472)
        self.lineEdit_11 = QtGui.QLineEdit(CFT)
        self.lineEdit_11.setGeometry(QtCore.QRect(1660, 1110, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName(_fromUtf8("lineEdit_11"))
        self.lineEdit_14 = QtGui.QLineEdit(CFT)
        self.lineEdit_14.setGeometry(QtCore.QRect(1660, 1290, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName(_fromUtf8("lineEdit_14"))
        self.label_12 = QtGui.QLabel(CFT)
        self.label_12.setGeometry(QtCore.QRect(990, 1290, 151, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_3 = QtGui.QLineEdit(CFT)
        self.lineEdit_3.setGeometry(QtCore.QRect(1200, 1170, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.lineEdit_2 = QtGui.QLineEdit(CFT)
        self.lineEdit_2.setGeometry(QtCore.QRect(1200, 1230, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.lineEdit_4 = QtGui.QLineEdit(CFT)
        self.lineEdit_4.setGeometry(QtCore.QRect(1200, 1110, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.label_11 = QtGui.QLabel(CFT)
        self.label_11.setGeometry(QtCore.QRect(990, 1230, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit = QtGui.QLineEdit(CFT)
        self.lineEdit.setGeometry(QtCore.QRect(1200, 1290, 441, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_10 = QtGui.QLabel(CFT)
        self.label_10.setGeometry(QtCore.QRect(990, 1170, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_15 = QtGui.QLineEdit(CFT)
        self.lineEdit_15.setGeometry(QtCore.QRect(1660, 1350, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName(_fromUtf8("lineEdit_15"))
        self.lineEdit_13 = QtGui.QLineEdit(CFT)
        self.lineEdit_13.setGeometry(QtCore.QRect(1660, 1230, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName(_fromUtf8("lineEdit_13"))
        self.label_9 = QtGui.QLabel(CFT)
        self.label_9.setGeometry(QtCore.QRect(990, 1110, 181, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_23 = QtGui.QLabel(CFT)
        self.label_23.setGeometry(QtCore.QRect(1320, 1350, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lineEdit_12 = QtGui.QLineEdit(CFT)
        self.lineEdit_12.setGeometry(QtCore.QRect(1660, 1170, 161, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName(_fromUtf8("lineEdit_12"))
        self.lbl_CFT = QtGui.QLabel(CFT)
        self.lbl_CFT.setGeometry(QtCore.QRect(150, 10, 581, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_CFT.setFont(font)
        self.lbl_CFT.setObjectName(_fromUtf8("lbl_CFT"))
        self.lne_day = QtGui.QLineEdit(CFT)
        self.lne_day.setGeometry(QtCore.QRect(290, 150, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_day.setFont(font)
        self.lne_day.setObjectName(_fromUtf8("lne_day"))
        self.lne_eID = QtGui.QLineEdit(CFT)
        self.lne_eID.setGeometry(QtCore.QRect(290, 100, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_eID.setFont(font)
        self.lne_eID.setText(_fromUtf8(""))
        self.lne_eID.setObjectName(_fromUtf8("lne_eID"))
        self.lbl_day = QtGui.QLabel(CFT)
        self.lbl_day.setGeometry(QtCore.QRect(20, 150, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        font.setItalic(True)
        self.lbl_day.setFont(font)
        self.lbl_day.setObjectName(_fromUtf8("lbl_day"))
        self.lbl_EID = QtGui.QLabel(CFT)
        self.lbl_EID.setGeometry(QtCore.QRect(20, 100, 211, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        self.lbl_EID.setFont(font)
        self.lbl_EID.setObjectName(_fromUtf8("lbl_EID"))
        self.lne_TCF = QtGui.QLineEdit(CFT)
        self.lne_TCF.setGeometry(QtCore.QRect(730, 350, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_TCF.setFont(font)
        self.lne_TCF.setObjectName(_fromUtf8("lne_TCF"))
        self.lbl_TCF = QtGui.QLabel(CFT)
        self.lbl_TCF.setGeometry(QtCore.QRect(310, 350, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.lbl_TCF.setFont(font)
        self.lbl_TCF.setObjectName(_fromUtf8("lbl_TCF"))
        self.btn_menu = QtGui.QPushButton(CFT)
        self.btn_menu.setGeometry(QtCore.QRect(20, 400, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_menu.setFont(font)
        self.btn_menu.setObjectName(_fromUtf8("btn_menu"))
        self.btn_save = QtGui.QPushButton(CFT)
        self.btn_save.setGeometry(QtCore.QRect(580, 400, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.btn_calc = QtGui.QPushButton(CFT)
        self.btn_calc.setGeometry(QtCore.QRect(650, 360, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_calc.setFont(font)
        self.btn_calc.setObjectName(_fromUtf8("btn_calc"))
        self.btn_clear = QtGui.QPushButton(CFT)
        self.btn_clear.setGeometry(QtCore.QRect(300, 400, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName(_fromUtf8("btn_clear"))
        self.lne_month = QtGui.QLineEdit(CFT)
        self.lne_month.setGeometry(QtCore.QRect(290, 200, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_month.setFont(font)
        self.lne_month.setObjectName(_fromUtf8("lne_month"))
        self.lbl_month = QtGui.QLabel(CFT)
        self.lbl_month.setGeometry(QtCore.QRect(20, 200, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        font.setItalic(True)
        self.lbl_month.setFont(font)
        self.lbl_month.setObjectName(_fromUtf8("lbl_month"))
        self.lne_year = QtGui.QLineEdit(CFT)
        self.lne_year.setGeometry(QtCore.QRect(290, 250, 561, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_year.setFont(font)
        self.lne_year.setObjectName(_fromUtf8("lne_year"))
        self.lbl_year = QtGui.QLabel(CFT)
        self.lbl_year.setGeometry(QtCore.QRect(20, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(18)
        font.setItalic(True)
        self.lbl_year.setFont(font)
        self.lbl_year.setObjectName(_fromUtf8("lbl_year"))
        self.lbl_mode = QtGui.QLabel(CFT)
        self.lbl_mode.setGeometry(QtCore.QRect(20, 300, 261, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.lbl_mode.setFont(font)
        self.lbl_mode.setObjectName(_fromUtf8("lbl_mode"))
        self.lne_mode = QtGui.QLineEdit(CFT)
        self.lne_mode.setGeometry(QtCore.QRect(290, 300, 431, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_mode.setFont(font)
        self.lne_mode.setObjectName(_fromUtf8("lne_mode"))
        self.lne_CF = QtGui.QLineEdit(CFT)
        self.lne_CF.setGeometry(QtCore.QRect(730, 300, 121, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_CF.setFont(font)
        self.lne_CF.setObjectName(_fromUtf8("lne_CF"))

        self.retranslateUi(CFT)
        QtCore.QMetaObject.connectSlotsByName(CFT)
    def retranslateUi(self, CFT):
        CFT.setWindowTitle(_translate("CFT", "Dialog", None))
        self.label_12.setText(_translate("CFT", "Saturday :", None))
        self.label_11.setText(_translate("CFT", "Friday :", None))
        self.label_10.setText(_translate("CFT", "Thursday :", None))
        self.label_9.setText(_translate("CFT", "Wednesday :", None))
        self.label_23.setText(_translate("CFT", "Total carbon footprints :", None))
        self.lbl_CFT.setText(_translate("CFT", "Carbon Footprint tracker", None))
        self.lbl_day.setText(_translate("CFT", "Day :", None))
        self.lbl_EID.setText(_translate("CFT", "Employee ID : ", None))
        self.lbl_TCF.setText(_translate("CFT", "Total carbon footprints :", None))
        self.btn_menu.setText(_translate("CFT", "Go back to menu", None))
        self.btn_save.setText(_translate("CFT", "Save", None))
        self.btn_calc.setText(_translate("CFT", "calc", None))
        self.btn_clear.setText(_translate("CFT", "Clear", None))
        self.lbl_month.setText(_translate("CFT", "Month :", None))
        self.lbl_year.setText(_translate("CFT", "Year :", None))
        self.lbl_mode.setText(_translate("CFT", "Mode of transport :", None))
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CFT = QtGui.QDialog()
    ui = Ui_CFT()
    ui.setupUi(CFT)
    CFT.show()
    sys.exit(app.exec_())

