from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
class Ui_EDB(object):
    def setupUi(self, EDB):
        EDB.setObjectName(_fromUtf8("EDB"))
        EDB.resize(1051, 544)
        self.btn_save = QtGui.QPushButton(EDB)
        self.btn_save.setGeometry(QtCore.QRect(210, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.lw_empl = QtGui.QListWidget(EDB)
        self.lw_empl.setGeometry(QtCore.QRect(310, 90, 731, 371))
        self.lw_empl.setObjectName(_fromUtf8("lw_empl"))
        self.btn_select = QtGui.QPushButton(EDB)
        self.btn_select.setGeometry(QtCore.QRect(400, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_select.setFont(font)
        self.btn_select.setObjectName(_fromUtf8("btn_select"))
        self.btn_menu = QtGui.QPushButton(EDB)
        self.btn_menu.setGeometry(QtCore.QRect(780, 470, 261, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        self.btn_menu.setFont(font)
        self.btn_menu.setObjectName(_fromUtf8("btn_menu"))
        self.btn_delete = QtGui.QPushButton(EDB)
        self.btn_delete.setGeometry(QtCore.QRect(590, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName(_fromUtf8("btn_delete"))
        self.btn_add = QtGui.QPushButton(EDB)
        self.btn_add.setGeometry(QtCore.QRect(10, 470, 191, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_add.setFont(font)
        self.btn_add.setObjectName(_fromUtf8("btn_add"))
        self.lbl_EDB = QtGui.QLabel(EDB)
        self.lbl_EDB.setGeometry(QtCore.QRect(310, 10, 441, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_EDB.setFont(font)
        self.lbl_EDB.setObjectName(_fromUtf8("lbl_EDB"))
        self.lbl_phone = QtGui.QLabel(EDB)
        self.lbl_phone.setGeometry(QtCore.QRect(10, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_phone.setFont(font)
        self.lbl_phone.setObjectName(_fromUtf8("lbl_phone"))
        self.lne_eID = QtGui.QLineEdit(EDB)
        self.lne_eID.setGeometry(QtCore.QRect(120, 100, 181, 31))
        self.lne_eID.setReadOnly(True)
        self.lne_eID.setObjectName(_fromUtf8("lne_eID"))
        self.lbl_zip = QtGui.QLabel(EDB)
        self.lbl_zip.setGeometry(QtCore.QRect(10, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_zip.setFont(font)
        self.lbl_zip.setObjectName(_fromUtf8("lbl_zip"))
        self.lne_phone = QtGui.QLineEdit(EDB)
        self.lne_phone.setGeometry(QtCore.QRect(120, 180, 181, 31))
        self.lne_phone.setObjectName(_fromUtf8("lne_phone"))
        self.lbl_adress = QtGui.QLabel(EDB)
        self.lbl_adress.setGeometry(QtCore.QRect(10, 300, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_adress.setFont(font)
        self.lbl_adress.setObjectName(_fromUtf8("lbl_adress"))
        self.lbl_name = QtGui.QLabel(EDB)
        self.lbl_name.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_name.setFont(font)
        self.lbl_name.setObjectName(_fromUtf8("lbl_name"))
        self.lne_name = QtGui.QLineEdit(EDB)
        self.lne_name.setGeometry(QtCore.QRect(120, 140, 181, 31))
        self.lne_name.setObjectName(_fromUtf8("lne_name"))
        self.lbl_age = QtGui.QLabel(EDB)
        self.lbl_age.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_age.setFont(font)
        self.lbl_age.setObjectName(_fromUtf8("lbl_age"))
        self.lbl_Eid = QtGui.QLabel(EDB)
        self.lbl_Eid.setGeometry(QtCore.QRect(10, 100, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_Eid.setFont(font)
        self.lbl_Eid.setObjectName(_fromUtf8("lbl_Eid"))
        self.lbl_email = QtGui.QLabel(EDB)
        self.lbl_email.setGeometry(QtCore.QRect(10, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_email.setFont(font)
        self.lbl_email.setObjectName(_fromUtf8("lbl_email"))
        self.lne_zip = QtGui.QLineEdit(EDB)
        self.lne_zip.setGeometry(QtCore.QRect(120, 340, 181, 31))
        self.lne_zip.setObjectName(_fromUtf8("lne_zip"))
        self.lne_email = QtGui.QLineEdit(EDB)
        self.lne_email.setGeometry(QtCore.QRect(120, 220, 181, 31))
        self.lne_email.setObjectName(_fromUtf8("lne_email"))
        self.lne_age = QtGui.QLineEdit(EDB)
        self.lne_age.setGeometry(QtCore.QRect(120, 260, 181, 31))
        self.lne_age.setObjectName(_fromUtf8("lne_age"))
        self.lne_adress = QtGui.QLineEdit(EDB)
        self.lne_adress.setGeometry(QtCore.QRect(120, 300, 181, 31))
        self.lne_adress.setObjectName(_fromUtf8("lne_adress"))
        self.lbl_salary = QtGui.QLabel(EDB)
        self.lbl_salary.setGeometry(QtCore.QRect(10, 380, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_salary.setFont(font)
        self.lbl_salary.setObjectName(_fromUtf8("lbl_salary"))
        self.lne_salary = QtGui.QLineEdit(EDB)
        self.lne_salary.setGeometry(QtCore.QRect(120, 380, 181, 31))
        self.lne_salary.setObjectName(_fromUtf8("lne_salary"))
        self.lbl_bonus = QtGui.QLabel(EDB)
        self.lbl_bonus.setGeometry(QtCore.QRect(10, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(12)
        self.lbl_bonus.setFont(font)
        self.lbl_bonus.setObjectName(_fromUtf8("lbl_bonus"))
        self.lne_bonus = QtGui.QLineEdit(EDB)
        self.lne_bonus.setGeometry(QtCore.QRect(120, 420, 181, 31))
        self.lne_bonus.setObjectName(_fromUtf8("lne_bonus"))
        self.retranslateUi(EDB)
        QtCore.QMetaObject.connectSlotsByName(EDB)
    def retranslateUi(self, EDB):
        EDB.setWindowTitle(_translate("EDB", "Dialog", None))
        self.btn_save.setText(_translate("EDB", "SAVE", None))
        self.btn_select.setText(_translate("EDB", "SELECT", None))
        self.btn_menu.setText(_translate("EDB", "go back to menu", None))
        self.btn_delete.setText(_translate("EDB", "DELETE", None))
        self.btn_add.setText(_translate("EDB", "ADD", None))
        self.lbl_EDB.setText(_translate("EDB", "Employee Database", None))
        self.lbl_phone.setText(_translate("EDB", "Phone", None))
        self.lbl_zip.setText(_translate("EDB", "Zip", None))
        self.lbl_adress.setText(_translate("EDB", "Adress", None))
        self.lbl_name.setText(_translate("EDB", "Name", None))
        self.lbl_age.setText(_translate("EDB", "Age", None))
        self.lbl_Eid.setText(_translate("EDB", "Employee ID", None))
        self.lbl_email.setText(_translate("EDB", "Email", None))
        self.lbl_salary.setText(_translate("EDB", "Salary", None))
        self.lbl_bonus.setText(_translate("EDB", "Bonus", None))
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EDB = QtGui.QDialog()
    ui = Ui_EDB()
    ui.setupUi(EDB)
    EDB.show()
    sys.exit(app.exec_())

