from PyQt4 import QtCore, QtGui
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s
try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)
class Ui_SBC(object):
    def setupUi(self, SBC):
        SBC.setObjectName(_fromUtf8("SBC"))
        SBC.resize(570, 393)
        self.lbl_SBC = QtGui.QLabel(SBC)
        self.lbl_SBC.setGeometry(QtCore.QRect(20, 20, 541, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Comic Sans MS"))
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_SBC.setFont(font)
        self.lbl_SBC.setObjectName(_fromUtf8("lbl_SBC"))
        self.lne_bonuspc = QtGui.QLineEdit(SBC)
        self.lne_bonuspc.setGeometry(QtCore.QRect(370, 160, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_bonuspc.setFont(font)
        self.lne_bonuspc.setObjectName(_fromUtf8("lne_bonuspc"))
        self.lbl_bonuspc = QtGui.QLabel(SBC)
        self.lbl_bonuspc.setGeometry(QtCore.QRect(20, 160, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.lbl_bonuspc.setFont(font)
        self.lbl_bonuspc.setObjectName(_fromUtf8("lbl_bonuspc"))
        self.lne_bonusmon = QtGui.QLineEdit(SBC)
        self.lne_bonusmon.setGeometry(QtCore.QRect(370, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_bonusmon.setFont(font)
        self.lne_bonusmon.setObjectName(_fromUtf8("lne_bonusmon"))
        self.lbl_bonus = QtGui.QLabel(SBC)
        self.lbl_bonus.setGeometry(QtCore.QRect(20, 220, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.lbl_bonus.setFont(font)
        self.lbl_bonus.setObjectName(_fromUtf8("lbl_bonus"))
        self.lne_tsalary = QtGui.QLineEdit(SBC)
        self.lne_tsalary.setGeometry(QtCore.QRect(370, 280, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_tsalary.setFont(font)
        self.lne_tsalary.setObjectName(_fromUtf8("lne_tsalary"))
        self.lbl_tsalary = QtGui.QLabel(SBC)
        self.lbl_tsalary.setGeometry(QtCore.QRect(20, 280, 321, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.lbl_tsalary.setFont(font)
        self.lbl_tsalary.setObjectName(_fromUtf8("lbl_tsalary"))
        self.lne_eID = QtGui.QLineEdit(SBC)
        self.lne_eID.setGeometry(QtCore.QRect(370, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Poor Richard"))
        font.setPointSize(16)
        font.setItalic(True)
        self.lne_eID.setFont(font)
        self.lne_eID.setObjectName(_fromUtf8("lne_eID"))
        self.lbl_eID = QtGui.QLabel(SBC)
        self.lbl_eID.setGeometry(QtCore.QRect(20, 100, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Stephen"))
        font.setPointSize(20)
        self.lbl_eID.setFont(font)
        self.lbl_eID.setObjectName(_fromUtf8("lbl_eID"))
        self.btn_calc = QtGui.QPushButton(SBC)
        self.btn_calc.setGeometry(QtCore.QRect(290, 110, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_calc.setFont(font)
        self.btn_calc.setObjectName(_fromUtf8("btn_calc"))
        self.btn_menu = QtGui.QPushButton(SBC)
        self.btn_menu.setGeometry(QtCore.QRect(10, 330, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_menu.setFont(font)
        self.btn_menu.setObjectName(_fromUtf8("btn_menu"))
        self.btn_save = QtGui.QPushButton(SBC)
        self.btn_save.setGeometry(QtCore.QRect(290, 330, 271, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Pirate"))
        font.setPointSize(16)
        font.setItalic(True)
        self.btn_save.setFont(font)
        self.btn_save.setObjectName(_fromUtf8("btn_save"))
        self.retranslateUi(SBC)
        QtCore.QMetaObject.connectSlotsByName(SBC)
    def retranslateUi(self, SBC):
        SBC.setWindowTitle(_translate("SBC", "Dialog", None))
        self.lbl_SBC.setText(_translate("SBC", "Salary Bonus Calculator", None))
        self.lbl_bonuspc.setText(_translate("SBC", "Bonus percentage :", None))
        self.lbl_bonus.setText(_translate("SBC", "Bonus (in Rs.) :", None))
        self.lbl_tsalary.setText(_translate("SBC", "Total Salary (in Rs.) :", None))
        self.lbl_eID.setText(_translate("SBC", "Employee ID :", None))
        self.btn_calc.setText(_translate("SBC", "Calc", None))
        self.btn_menu.setText(_translate("SBC", "Go back to menu", None))
        self.btn_save.setText(_translate("SBC", "Save", None))
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    SBC = QtGui.QDialog()
    ui = Ui_SBC()
    ui.setupUi(SBC)
    SBC.show()
    sys.exit(app.exec_())

